[package]
name = "guntamatic-web"
version = "0.1.0"
authors = ["geropl <gero.posmyk@posteo.de>"]
edition = "2024"
description = "HTTP/Web client for Guntamatic heating devices"
repository = "https://github.com/swimmes/guntamatic"
license = "MIT OR Apache-2.0"
keywords = ["guntamatic", "http", "web", "iot", "monitoring"]
categories = ["hardware-support", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "guntamatic_web"
path = "src/lib/mod.rs"

[dependencies]
guntamatic-core = { path = "../guntamatic-core" }

reqwest = { workspace = true, features = ["json", "rustls", "webpki-roots"] }
http = { workspace = true }
http-types = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
serde_repr = { workspace = true }

log = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
