[package]
name = "guntamatic-cli"
version = "0.3.0"
authors = ["swimmes <wimmesberger@gmail.com>", "geropl <gero.posmyk-leinemann@typefox.io>"]
edition = "2024"
description = "CLI tool to connect to and extract data from Guntamatic heating devices"
repository = "https://github.com/swimmes/guntamatic"
license = "MIT OR Apache-2.0"
keywords = ["guntamatic", "heating", "modbus", "iot", "monitoring"]
categories = ["command-line-utilities", "hardware-support"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("sink_prometheus"))'] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "guntamatic"
path = "src/main.rs"

[features]
default = ["sink_influxdb"]
sink_influxdb = ["influxdb2"]
sink_influxdb3 = ["influxdb3-client"]
# sink_prometheus = ["prometheus", "warp"]


[dependencies]
guntamatic-core = { path = "../guntamatic-core" }
guntamatic-web = { path = "../guntamatic-web" }
guntamatic-modbus = { path = "../guntamatic-modbus" }

clap = { workspace = true }

# error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# logging
env_logger = { workspace = true }
log = { workspace = true }

# runtime + support
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }
tokio-stream = { workspace = true }
ctrlc = { workspace = true }
flume = { workspace = true }

# # sink_prometheus
# prometheus = { version = "0.11.0", optional = true }
# warp = { version = "0.3.0", optional = true }

# sink_influxdb
influxdb2 = { workspace = true, optional = true }

# sink_influxdb3
influxdb3-client = { workspace = true, optional = true }

# misc
hex = { workspace = true }
pretty_assertions = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
